
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package br.ufpe.cin.greco.devc.languageStructure.treq;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_INTERNAL = 64;
  public static final int T_MEMORY = 77;
  public static final int T_CRITICAL = 72;
  public static final int T_PATTERN = 25;
  public static final int T_FALSE = 59;
  public static final int T_CLOSE_PAR = 3;
  public static final int T_OPER = 33;
  public static final int T_LLTLF = 44;
  public static final int T_MIN_DELAY = 20;
  public static final int T_NS = 30;
  public static final int T_BOOL_EQUI = 47;
  public static final int T_BOOL_IMPL = 46;
  public static final int T_WEAK_UNTIL_OPER = 54;
  public static final int T_UNTIL_OPER = 53;
  public static final int T_ADD_EXIT_POINT = 41;
  public static final int T_RSHIFT = 71;
  public static final int T_MASKREP = 13;
  public static final int T_DIV = 63;
  public static final int T_ORTHO_STATE = 38;
  public static final int T_WRITE = 15;
  public static final int T_ALIAS = 23;
  public static final int T_READ = 14;
  public static final int T_GLOBAL_STATE = 37;
  public static final int T_DOT = 9;
  public static final int T_IGUAL = 8;
  public static final int T_INT = 34;
  public static final int T_LSHIFT = 70;
  public static final int T_BOOL_CONJ = 48;
  public static final int T_MASK = 26;
  public static final int T_MS = 28;
  public static final int T_STATE = 35;
  public static final int T_CLOSE_BRACKET = 11;
  public static final int T_EXTERNAL = 65;
  public static final int T_DC_FORMAT = 22;
  public static final int T_TEXTSTR = 45;
  public static final int T_OPEN_BRACE = 6;
  public static final int T_ADD_PROPERTY = 40;
  public static final int T_VIRG = 12;
  public static final int T_REGWRITE = 66;
  public static final int T_ADD_BEHAVIOR = 76;
  public static final int T_COMP_OPER = 68;
  public static final int T_MINUS = 61;
  public static final int T_SEC = 27;
  public static final int T_ALWAYS_OPER = 50;
  public static final int T_INITIAL_STATE = 36;
  public static final int T_REGREAD = 67;
  public static final int T_COMP = 69;
  public static final int T_IDENT = 32;
  public static final int T_MAX_DELAY = 19;
  public static final int T_READWRITE = 16;
  public static final int T_WARNING = 73;
  public static final int T_DC_REG = 17;
  public static final int T_DEVICE = 24;
  public static final int T_DOISPONTOS = 5;
  public static final int T_OPEN_PAR = 2;
  public static final int T_TRUE = 58;
  public static final int EOF = 0;
  public static final int T_NEXT_OPER = 51;
  public static final int T_PLUS = 60;
  public static final int T_BOOL_DISJ = 49;
  public static final int T_ADD_ENTRY_POINT = 42;
  public static final int T_MULT = 62;
  public static final int error = 1;
  public static final int T_PONTVIRG = 4;
  public static final int T_RESERVED = 18;
  public static final int T_EVENT_OPER = 52;
  public static final int T_PS = 31;
  public static final int T_LTLF = 43;
  public static final int T_OPEN_BRACKET = 10;
  public static final int T_INFO = 74;
  public static final int T_CLOSE_BRACE = 7;
  public static final int T_DUAL_UNTIL_OPER = 55;
  public static final int T_ORTHO_REGION = 39;
  public static final int T_PROP_NEG_OPER = 57;
  public static final int T_VAR = 75;
  public static final int T_US = 29;
  public static final int T_ASSIGNS = 56;
  public static final int T_IMPORT = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_OPEN_PAR",
  "T_CLOSE_PAR",
  "T_PONTVIRG",
  "T_DOISPONTOS",
  "T_OPEN_BRACE",
  "T_CLOSE_BRACE",
  "T_IGUAL",
  "T_DOT",
  "T_OPEN_BRACKET",
  "T_CLOSE_BRACKET",
  "T_VIRG",
  "T_MASKREP",
  "T_READ",
  "T_WRITE",
  "T_READWRITE",
  "T_DC_REG",
  "T_RESERVED",
  "T_MAX_DELAY",
  "T_MIN_DELAY",
  "T_IMPORT",
  "T_DC_FORMAT",
  "T_ALIAS",
  "T_DEVICE",
  "T_PATTERN",
  "T_MASK",
  "T_SEC",
  "T_MS",
  "T_US",
  "T_NS",
  "T_PS",
  "T_IDENT",
  "T_OPER",
  "T_INT",
  "T_STATE",
  "T_INITIAL_STATE",
  "T_GLOBAL_STATE",
  "T_ORTHO_STATE",
  "T_ORTHO_REGION",
  "T_ADD_PROPERTY",
  "T_ADD_EXIT_POINT",
  "T_ADD_ENTRY_POINT",
  "T_LTLF",
  "T_LLTLF",
  "T_TEXTSTR",
  "T_BOOL_IMPL",
  "T_BOOL_EQUI",
  "T_BOOL_CONJ",
  "T_BOOL_DISJ",
  "T_ALWAYS_OPER",
  "T_NEXT_OPER",
  "T_EVENT_OPER",
  "T_UNTIL_OPER",
  "T_WEAK_UNTIL_OPER",
  "T_DUAL_UNTIL_OPER",
  "T_ASSIGNS",
  "T_PROP_NEG_OPER",
  "T_TRUE",
  "T_FALSE",
  "T_PLUS",
  "T_MINUS",
  "T_MULT",
  "T_DIV",
  "T_INTERNAL",
  "T_EXTERNAL",
  "T_REGWRITE",
  "T_REGREAD",
  "T_COMP_OPER",
  "T_COMP",
  "T_LSHIFT",
  "T_RSHIFT",
  "T_CRITICAL",
  "T_WARNING",
  "T_INFO",
  "T_VAR",
  "T_ADD_BEHAVIOR",
  "T_MEMORY"
  };
}

